spring:
  thymeleaf:
    mode: HTML

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.22.136:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: yinxin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
logging:
   level:
     root: info
     com.myx: debug
   file: log/myblog.log
   
server:  
  port: 443
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8 
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 56844813
    keyStoreType: PKCS12
    keyAlias: tomcat
    